name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WEB_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/web

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    container: docker:stable
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set environment variables
        run: |
          echo "WEB_IMAGE=$(echo ${{env.WEB_IMAGE}} )" >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
      - name: Pull images
        run: |
          docker pull $WEB_IMAGE:latest || true
      - name: Build images
        run: |
          docker build --cache-from $WEB_IMAGE:latest --tag $WEB_IMAGE:latest --file ./Dockerfile "."
      - name: Push images
        run: |
          docker push $WEB_IMAGE:latest
          
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
    env:
      POSTGRES_DB: test
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""
      DATABASE_URL: postgres://runner@postgres:5432/test
    steps:
      - name: Log in to GitHub Packages
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
      - name: Pull images
        run: |
          docker pull $WEB_IMAGE:latest || true
      - name: Tests
        run: |
          docker run aaaaaaaaa:latest --name web
          docker exec web python manage.py test
          flake8 hello_django --max-line-length=100
          black hello_django --check
          isort hello_django --check
          
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Deploy
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y ruby-dev
          sudo gem install dpl
          sudo dpl --provider=heroku --app=${{ secrets.HEROKU_APP_NAME }} --api-key=${{ secrets.HEROKU_AUTH_TOKEN }}
